<a href="https://colab.research.google.com/github/AnnanyaV/kaggle/blob/master/IPL_IIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!unzip /content/drive/MyDrive/IITData/ipl_csv2.zip

In [4]:
df3= pd.read_csv('all_matches.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
df3.head()

match_id   season  ... other_wicket_type other_player_dismissed
0    335982  2007/08  ...               NaN                    NaN
1    335982  2007/08  ...               NaN                    NaN
2    335982  2007/08  ...               NaN                    NaN
3    335982  2007/08  ...               NaN                    NaN
4    335982  2007/08  ...               NaN                    NaN

[5 rows x 22 columns]

VENUE PREPROCESSING

In [ ]:
stadiums= df3["venue"].value_counts()
print(stadiums)

In [7]:
venue_list= df3['venue'].unique()
venue_list

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Eden Gardens', 'Wankhede Stadium', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket St

In [8]:
d_venue={}
for i in range(len(venue_list)):
  d_venue[venue_list[i]]=i

In [9]:
df3['venue']= df3['venue'].replace(d_venue)


In [10]:
df3['venue'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

BATTING TEAM AND BOWLING TEAM PREPROCESSING

In [11]:
def preprocessing(x):
  x_list= df3[x].unique()
  d={}
  for i in range(len(x_list)):
    d[x_list[i]]=i

  return df3[x].replace(d)
  


In [12]:
batting_team_list= df3['batting_team'].unique()
d_batting_team={}
for i in range(len(batting_team_list)):
  d_batting_team[batting_team_list[i]]=i
df3['batting_team']= df3['batting_team'].replace(d_batting_team)

In [13]:
bowling_team_list= df3['bowling_team'].unique()
d_bowling_team={}
for i in range(len(bowling_team_list)):
  d_bowling_team[bowling_team_list[i]]=i
df3['bowling_team']= df3['bowling_team'].replace(d_bowling_team)

In [14]:
df3.bowling_team.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

STRIKER PREPROCESSING

In [15]:
# df3['striker']= preprocessing('striker')


BOWLER PREPROCESSING

In [16]:
# df3['bowler']= preprocessing('bowler')

In [17]:
df3

match_id   season  ... other_wicket_type  other_player_dismissed
0         335982  2007/08  ...               NaN                     NaN
1         335982  2007/08  ...               NaN                     NaN
2         335982  2007/08  ...               NaN                     NaN
3         335982  2007/08  ...               NaN                     NaN
4         335982  2007/08  ...               NaN                     NaN
...          ...      ...  ...               ...                     ...
194349   1254060     2021  ...               NaN                     NaN
194350   1254060     2021  ...               NaN                     NaN
194351   1254060     2021  ...               NaN                     NaN
194352   1254060     2021  ...               NaN                     NaN
194353   1254060     2021  ...               NaN                     NaN

[194354 rows x 22 columns]

In [18]:
sum_column = df3["runs_off_bat"] + df3["extras"]
df3["total_runs_per_ball"] = sum_column
df3['total_runs_per_ball'].unique()

array([1, 0, 4, 6, 5, 2, 3, 7])

In [19]:
df3['wides'] = df3['wides'].fillna(0)
df3['noballs'] = df3['noballs'].fillna(0)
df3['byes'] = df3['byes'].fillna(0)
df3['legbyes'] = df3['legbyes'].fillna(0)
df3['penalty'] = df3['penalty'].fillna(0)

In [20]:
df3.drop(['wides', 'noballs', 'byes', 'legbyes', 'penalty'], axis=1, inplace=True)

In [21]:
df3.drop(['player_dismissed','other_wicket_type','other_player_dismissed'],axis=1,inplace=True)
df3.head()

match_id   season  start_date  ...  extras  wicket_type  total_runs_per_ball
0    335982  2007/08  2008-04-18  ...       1          NaN                    1
1    335982  2007/08  2008-04-18  ...       0          NaN                    0
2    335982  2007/08  2008-04-18  ...       1          NaN                    1
3    335982  2007/08  2008-04-18  ...       0          NaN                    0
4    335982  2007/08  2008-04-18  ...       0          NaN                    0

[5 rows x 15 columns]

In [22]:
df3['match_id'] = preprocessing('match_id')

In [23]:
df3.drop('season', axis=1, inplace=True)


In [24]:
df3 = df3[df3['ball']<6.0]


In [25]:
df3.head()

match_id  start_date  venue  ...  extras  wicket_type  total_runs_per_ball
0         0  2008-04-18      0  ...       1          NaN                    1
1         0  2008-04-18      0  ...       0          NaN                    0
2         0  2008-04-18      0  ...       1          NaN                    1
3         0  2008-04-18      0  ...       0          NaN                    0
4         0  2008-04-18      0  ...       0          NaN                    0

[5 rows x 14 columns]

In [26]:
df3['ball'].unique()

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
       4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 2.7,
       1.7, 5.7, 5.8, 1.8, 4.7, 3.8, 0.8, 2.8, 1.9, 5.9, 4.8, 0.9, 3.9,
       4.9, 2.9])

In [27]:
df3.drop(['start_date', 'wicket_type', 'runs_off_bat', 'extras'], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [28]:
df3.head()

match_id  venue  innings  ...  non_striker   bowler  total_runs_per_ball
0         0      0        1  ...  BB McCullum  P Kumar                    1
1         0      0        1  ...   SC Ganguly  P Kumar                    0
2         0      0        1  ...   SC Ganguly  P Kumar                    1
3         0      0        1  ...   SC Ganguly  P Kumar                    0
4         0      0        1  ...   SC Ganguly  P Kumar                    0

[5 rows x 10 columns]

In [29]:
df1=df3

In [30]:
df1.head()

match_id  venue  innings  ...  non_striker   bowler  total_runs_per_ball
0         0      0        1  ...  BB McCullum  P Kumar                    1
1         0      0        1  ...   SC Ganguly  P Kumar                    0
2         0      0        1  ...   SC Ganguly  P Kumar                    1
3         0      0        1  ...   SC Ganguly  P Kumar                    0
4         0      0        1  ...   SC Ganguly  P Kumar                    0

[5 rows x 10 columns]

STRIKERS PREPROCESSING


In [31]:
strikers_main_list= df1['striker'].unique()
d_strikers={}
for i in range(df1.shape[0]):
  if df1.iloc[i, 6] in d_strikers.keys():
    d_strikers[df1.iloc[i, 6]]=d_strikers[df1.iloc[i, 6]]+df1.iloc[i, 9]
  else:
    d_strikers[df1.iloc[i, 6]]= df1.iloc[i, 9]

df3['striker']=df3['striker'].replace(d_strikers)



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [32]:
df3.head()

match_id  venue  innings  ...  non_striker   bowler  total_runs_per_ball
0         0      0        1  ...  BB McCullum  P Kumar                    1
1         0      0        1  ...   SC Ganguly  P Kumar                    0
2         0      0        1  ...   SC Ganguly  P Kumar                    1
3         0      0        1  ...   SC Ganguly  P Kumar                    0
4         0      0        1  ...   SC Ganguly  P Kumar                    0

[5 rows x 10 columns]

BOWLERS PREPROCESSING

In [33]:
bowlers_main_list= df1['bowler'].unique()
d_bowlers={}
for i in range(df1.shape[0]):
  if df1.iloc[i, 8] in d_bowlers.keys():
    d_bowlers[df1.iloc[i, 8]]=d_bowlers[df1.iloc[i, 8]]+df1.iloc[i, 9]
  else:
    d_bowlers[df1.iloc[i, 8]]= df1.iloc[i, 9]
df3['bowler']=df3['bowler'].replace(d_bowlers)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [34]:
go= df3.groupby('match_id')
matches= df3['match_id'].unique()
last_ball_df= go.last('ball')
last_ball= list(last_ball_df['ball'])



In [35]:
last_ball= list(last_ball_df['ball'])


In [36]:
go= df3.groupby('match_id')
matches= df3['match_id'].unique()
last_ball_df= go.last('ball')
last_ball= list(last_ball_df['ball'])
last_ball
for i in matches:
  globals()['dfnew%s' %i] = go.get_group(i)





In [37]:
final_df_main= pd.DataFrame(columns = ['match_id', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 
                                 'bowler', 'total_runs'])
def newdataframe(dataframe, x, final_df):
  i=0
  striker_list=[]
  bowler_list=[]
  runs= 0
  while(dataframe.iloc[i,2]<dataframe.iloc[i+1,2]):
    striker_list.append(dataframe.iloc[i,5])
    bowler_list.append(dataframe.iloc[i,7])
    runs= runs+dataframe.iloc[i,8]
    i=i+1
  strikers=set(striker_list)
  bowlers= set(bowler_list)
  df_to_append= {'match_id':x, 'venue':dataframe.iloc[i-1, 0], 'innings':1, 'ball':dataframe.iloc[i-1,2], 'batting_team':dataframe.iloc[i-1,3], 
                 'bowling_team':dataframe.iloc[i-1,4], 'striker':list(strikers), 'bowler':list(bowlers), 'total_runs':runs}
  final_df= final_df.append(df_to_append, ignore_index = True)
  striker_list=[]
  bowler_list=[]
  runs= 0
  while(i<dataframe.shape[0]):
    striker_list.append(dataframe.iloc[i,5])
    bowler_list.append(dataframe.iloc[i,7])
    runs= runs+dataframe.iloc[i,8]
    i=i+1
  strikers=set(striker_list)
  bowlers= set(bowler_list)
  df_to_append= {'match_id':x, 'venue':dataframe.iloc[i-1, 0], 'innings':2, 'ball':dataframe.iloc[i-1,2], 'batting_team':dataframe.iloc[i-1,3], 
                 'bowling_team':dataframe.iloc[i-1,4], 'striker':list(strikers), 'bowler':list(bowlers), 'total_runs':runs}
  final_df= final_df.append(df_to_append, ignore_index = True)
  return final_df

    

    

    







    

In [38]:
m=0
while(m<=240):
  if(m in matches):
    final_df_main= newdataframe(globals()['dfnew%s' %m], m, final_df_main)
  m=m+1


In [39]:
m=243
while(m<=485):
  if(m in matches):
    final_df_main= newdataframe(globals()['dfnew%s' %m], m, final_df_main)
    
  m=m+1

In [40]:
m=487
while(m<=818):
  if(m in matches):
    final_df_main= newdataframe(globals()['dfnew%s' %m], m, final_df_main)
    
  m=m+1

In [41]:
final_df_main.head()

match_id venue  ...                   bowler  total_runs
0        0     0  ...         [1492, 1813, 23]          61
1        0     0  ...  [1010, 1492, 1493, 295]          26
2        1     1  ...           [26, 739, 580]          53
3        1     1  ...           [722, 26, 173]          63
4        2     2  ...           [218, 212, 50]          40

[5 rows x 9 columns]

In [42]:
def average(list1):
  return sum(list1)/len(list1)

In [43]:
final_df_main['striker']= final_df_main['striker'].apply(lambda x: average(x))


In [44]:
final_df_main['bowler']= final_df_main['bowler'].apply(lambda x: average(x))

In [45]:
final_df_main.head()

match_id venue innings  ...      striker       bowler total_runs
0        0     0       1  ...   770.000000  1109.333333         61
1        0     0       2  ...   597.142857  1072.500000         26
2        1     1       1  ...  1190.000000   448.333333         53
3        1     1       2  ...   410.000000   307.000000         63
4        2     2       1  ...   481.000000   160.000000         40

[5 rows x 9 columns]

ARIMA MODEL

In [ ]:
arima_df = final_df_main['total_runs']

In [ ]:
arima_df.describe()

count     1632
unique      78
top         45
freq        68
Name: total_runs, dtype: int64

In [ ]:
!pip install pmdarima

     |████████████████████████████████| 1.5MB 4.3MB/s 
     |████████████████████████████████| 9.5MB 20.9MB/s 
  Found existing installation: statsmodels 0.10.2
    Uninstalling statsmodels-0.10.2:
      Successfully uninstalled statsmodels-0.10.2


In [ ]:
from pmdarima import auto_arima

In [ ]:
stepwise_model = auto_arima(arima_df, start_p=1, start_q=1,
                           max_p=3, max_q=3, m=12,
                           start_P=0, seasonal=True,
                           d=1, D=1, trace=True,
                           error_action='ignore',  
                           suppress_warnings=True, 
                           stepwise=True)

Performing stepwise search to minimize aic
 ARIMA(1,1,1)(0,1,1)[12]             : AIC=inf, Time=8.90 sec
 ARIMA(0,1,0)(0,1,0)[12]             : AIC=14715.273, Time=0.09 sec
 ARIMA(1,1,0)(1,1,0)[12]             : AIC=13824.717, Time=0.95 sec
 ARIMA(0,1,1)(0,1,1)[12]             : AIC=inf, Time=4.02 sec
 ARIMA(1,1,0)(0,1,0)[12]             : AIC=14255.026, Time=0.18 sec
 ARIMA(1,1,0)(2,1,0)[12]             : AIC=13627.265, Time=2.18 sec


In [ ]:
stepwise_model.aic()

In [ ]:
train = arima_df.loc[0:1305]

In [ ]:
test = arima_df.loc[1306:]

In [ ]:
test.describe()

In [ ]:
stepwise_model.fit(train)

In [ ]:
future_forecast = stepwise_model.predict(n_periods=326)

In [ ]:
future_forecast = pd.DataFrame(future_forecast,index = test.index,columns=['Prediction'])

In [ ]:
future_forecast.head()

In [ ]:
test.head()

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(test, future_forecast)
rmse = np.sqrt(mse)
rmse

LINEAR REGRESSION

In [45]:
from sklearn.preprocessing import StandardScaler
data= final_df_main
scaler = StandardScaler()
new_df_main= scaler.fit_transform(data.iloc[:, :-1])

In [46]:
final_df_main1 = pd.DataFrame(new_df_main, columns = ['','match_id',	'venue',	'innings	ball',	'batting_team',	'bowling_team',	'striker',	'bowler'])

In [47]:
final_df_main1['total_runs']= final_df_main['total_runs']
final_df_main= final_df_main1

In [48]:
final_df_main.head()

match_id  venue  ...   striker    bowler  total_runs
0 -1.729275 -1.049566   -1.0  ... -0.653844  1.896546          61
1 -1.729275 -1.049566    1.0  ... -1.034132  1.744702          26
2 -1.725050 -0.970060   -1.0  ...  0.270163 -0.828405          53
3 -1.725050 -0.970060    1.0  ... -1.445849 -1.411047          63
4 -1.720825 -0.890553   -1.0  ... -1.289648 -2.017049          40

[5 rows x 9 columns]

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(final_df_main.iloc[:, 0:8], final_df_main.iloc[:,8], test_size = 0.25)
  
# Splitting the data into training and testing data

In [50]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
  
regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

0.1294753340766458


In [ ]:
y_pred

In [52]:
from sklearn.metrics import mean_squared_error
y_pred = regr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

11.507976467489774

SVR

In [58]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [59]:
y_pred = regressor.predict(X_test)
y_pred = y_pred.astype(int)

In [60]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

11.519378387368501

RANDOM FOREST CLASSIFIER

In [54]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, max_depth=20, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=20, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [55]:
# Use the forest's predict method on the test data
y_pred = rf.predict(X_test)
y_pred = y_pred.astype(int)
score = rf.score(X_train, y_train)
score2 = rf.score(X_test, y_test)
print("Training set accuracy: ", '%.3f'%(score)) 
print("Test set accuracy: ", '%.3f'%(score2))

Training set accuracy:  0.872
Test set accuracy:  0.131


In [56]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

11.564397698006026

In [57]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.12091840385299735